### ISSUE TITLE
Release v3.0 tracking issue

### ISSUE THREAD

**Issue by Lakitna** [Lakitna/Mocha-bundle-ui#15]
- [x] General improvements in stability and readability | PR: #14
- [x] Bundle on strings | Issue: #10 PR: #11 
- [x] Allow bundles to work in a `then` block | Issue: #12 PR: #17 
- [x] ~~Default bundle values for object-based bundles. | Issue: #20 (requires investigation, removes limitation)~~
- [x] Make `done()` optional for `bundle.beforeEach` and `before.afterEach`. | Issue: #18 PR: #21 
- [ ] Split up and improve documentation for every supported UIs. | Issue: #19 PR: #22
